var express = require("express");
var router = express.Router();
var api = require('./api');
var fs = require('fs');

var multer = require("multer")

// const Storage = multer.diskStorage({
//     destination(req, file, callback) { 
//       callback(null, '/home/com115/Desktop/kuchBhi/posts')
//     },
//     filename(req, file, callback) {
//         console.log("in multer_______>>>",req.body);
//       callback(null, `${file.fieldname}_${Date.now()}_${file.originalname}`)
//     },
//   })

// const upload = multer({ storage: Storage })

var upload = multer({ dest: './posts' }); //setting the default folder for multer
//other imports and code will go here
router.post('/uploadPost',upload.single('fileData'), (req, res,next) => {
  logger.info(req.file);//this will be automatically set by multer
  logger.info(req.body);
  //below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
  fs.readFile(req.file.path,(err, contents)=> {
   if (err) {
   console.log('Error: ', err);
  }else{
   console.log('File contents ',contents);
  }
 });
});

router.post('/signUp',function(req,res){
    console.log("data before error::::",req.body)
    try
    {
        api.signUp(req.body).then((data)=>{

            res.send(data);
        });
    }
    catch(err){
        res.send(err);
    }
 
    
})

router.post("/login",function(req,res){
    console.log("loginnnnnnnnnnnnnn",req.body);

    try
    {
        api.login(req.body).then((data)=>{

            res.send(data);
        })
    }
    catch(err)
    {
        res.send(err);
    }
})

// router.post("/uploadPost",upload.single("fileData"),function(req,res){
    
//         console.log("in uploadpost^^^^^^^^",req.body);

//         res.send({message:"post uploaded"});
    
// })

// router.post('/addComment', (req, res) => {

//     try {
//         api.Addcomment(req.body).then((data) => {
//             res.send(req.body);
//         })
//     }
//     catch (err) {
//         res.send(err);
//     }
// })

// router.post('/getComments', (req, res) => {
//     try {
//         api.Getcomments(req.body).then((data) => {

//             res.send(data);
//         })

//     }
//     catch (err) {
//         res.send(err);
//     }
// })

// router.post('/getlikes', (req, res) => {
//     console.log("data for likes __________________",req.body);
//     try {
//         api.Getlikes(req.body).then((data) => {

//             console.log("likes from apiiiiiiiiiiii areeeeeeeee",data);

//             res.send({ temp: data[0].likes.length })
//         })
//     }
//     catch (err) {
//         res.send(err);
//     }
// })

// router.post('/onlike', (req, res) => {
//     try {
//         api.Onlike(req.body).then((data) => {

//             res.send(data);
//         })
//     }
//     catch (err) {
//         res.send(err);
//     }
// })
module.exports = router;